### ISSUE TITLE
source not able to be used

### ISSUE THREAD

**Issue by saturite** [vqea/fulcrum#1]
When I correctly download all modules and start the bot, immidiately in console it says discord.ext.commands.errors.ExtensionNotFound: Extension 'jishaku' could not be loaded. As someone who doesn't put time at all into code, I think you should put all the right installed modules in a requirement.txt file and fix the main code.

**Comment by vqea** [comment]
why would i make a file for requirements not like its mine lol it’s not hard to install the requirement

**Comment by saturite** [comment]
> why would i make a file for requirements not like its mine lol it’s not hard to install the requirement

because the file doesn't work 💀 , please needed requirements to start the bot, don't even work

**Comment by vqea** [comment]
> > why would i make a file for requirements not like its mine lol it’s not hard to install the requirement
> 
> 
> 
> because the file doesn't work 💀 , please needed requirements to start the bot, don't even work

not my source code 😱 like i totally didn't just say tht

**Comment by saturite** [comment]
> > > why would i make a file for requirements not like its mine lol it’s not hard to install the requirement
> > 
> > 
> > because the file doesn't work 💀 , please needed requirements to start the bot, don't even work
> 
> not my source code 😱 like i totally didn't just say tht

I can obviously read 😭 , just saying is better cuz ian know how to start this sh source w out all the errors in console.
